{
 "title": "Router Example Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Operation Cache Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cache Sizes (In Cost)",
   "type": "stat",
   "description": "Cost defines how many items can be inserted into the cache. Upon insertion a cost for an item is provided and calcuated against the remaining cost. If the insertion would exceed the cost, the cache wil start evicting items.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_graphql_cache_cost_max{cache_type=\"plan\"}",
     "legendFormat": "Plan"
    },
    {
     "expr": "router_graphql_cache_cost_max{cache_type=\"validation\"}",
     "legendFormat": "Validation"
    },
    {
     "expr": "router_graphql_cache_cost_max{cache_type=\"query_normalization\"}",
     "legendFormat": "Query Normalization"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(cache_type) (increase(router_graphql_cache_requests_stats_total{type=\"hits\"} [1h]))\n/\nsum by(cache_type) (increase(router_graphql_cache_requests_stats_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(router_graphql_cache_requests_stats_total{cache_type=\"plan\" ,type=\"hits\"}[2h])) /\nsum(rate(router_graphql_cache_requests_stats_total{cache_type=\"plan\"}[2h]))",
     "legendFormat": "Plan"
    },
    {
     "expr": "sum(rate(router_graphql_cache_requests_stats_total{cache_type=\"validation\" ,type=\"hits\"}[2h])) /\nsum(rate(router_graphql_cache_requests_stats_total{cache_type=\"validation\"}[2h]))",
     "legendFormat": "Validation"
    },
    {
     "expr": "sum(rate(router_graphql_cache_requests_stats_total{cache_type=\"query_normalization\" ,type=\"hits\"}[2h])) /\nsum(rate(router_graphql_cache_requests_stats_total{cache_type=\"query_normalization\"}[2h]))",
     "legendFormat": "Query Normalization"
    }
   ]
  },
  {
   "title": "Cost Operations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(cache_type, operation)(increase(router_graphql_cache_cost_stats_total{cache_type=\"plan\"} [1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(cache_type, operation)(increase(router_graphql_cache_cost_stats_total{cache_type=\"validation\"} [1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(cache_type, operation)(increase(router_graphql_cache_cost_stats_total{cache_type=\"query_normalization\"} [1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Operations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(cache_type, operation)(increase(router_graphql_cache_keys_stats_total{cache_type=\"plan\"} [1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(cache_type, operation)(increase(router_graphql_cache_keys_stats_total{cache_type=\"validation\"} [1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(cache_type, operation)(increase(router_graphql_cache_keys_stats_total{cache_type=\"query_normalization\"} [1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Router Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  }
 ]
}